const data=[
['moderation','🛡️','ban','Ban a member','Moderation'],['moderation','🔇','mute','Mute a member','Moderation'],['moderation','🔓','unmute','Unmute a member','Moderation'],['moderation','🧹','clear','Clear messages','Moderation'],['moderation','🔒','lock','Lock a channel','Moderation'],['moderation','📜','logs','View server logs','Moderation'],
['community','🎫','ticket','Open a support ticket','Community'],['community','👋','welcome','Configure welcome tools','Community'],['community','⭐','suggest','Send a suggestion','Community'],['community','📊','poll','Create a poll','Community'],['community','💍','marry','Marriage & social system','Community'],['community','🎉','giveaway','Run a giveaway','Community'],
['utility','❓','help','Open the RET help center','Utility'],['utility','🤖','botinfo','View RET information','Utility'],['utility','📈','serverinfo','View server information','Utility'],['utility','⏰','remind','Create a reminder','Utility'],['utility','👤','profile','View a member profile','Utility'],['utility','🏆','rank','View rankings','Utility'],
['fun','🎮','rps','Rock Paper Scissors','Fun'],['fun','🪙','coinflip','Flip a coin','Fun'],['fun','🎲','dice','Roll dice','Fun'],['fun','🧩','trivia','Play trivia','Fun'],['fun','❓','riddle','Get a riddle','Fun'],['fun','🎯','guess','Guessing game','Fun']
];
const list=document.getElementById('commandsList'), search=document.getElementById('commandSearch'); let cat='all';
function render(){const q=(search.value||'').toLowerCase();list.innerHTML=data.filter(x=>(cat==='all'||x[0]===cat)&&(!q||x.join(' ').toLowerCase().includes(q))).map(x=>`<article class="cmd"><span>${x[1]}</span><div><b>!${x[2]}</b><small>${x[3]}</small></div><label>${x[4]}</label></article>`).join('')||'<div class="empty">No commands matched your search.</div>';}
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');cat=b.dataset.cat;render()}); search.oninput=render; render();
document.querySelector('.menu').onclick=()=>document.querySelector('.nav nav').classList.toggle('open');
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('show')}),{threshold:.08});document.querySelectorAll('.reveal').forEach(x=>io.observe(x));
document.addEventListener('pointermove',e=>{document.documentElement.style.setProperty('--mx',e.clientX+'px');document.documentElement.style.setProperty('--my',e.clientY+'px')});
